# Generated by Django 4.0.6 on 2022-10-26 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appEcoindustry', '0004_comentario_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('placa', models.AutoField(primary_key=True, serialize=False)),
                ('nombreConductor', models.CharField(max_length=45)),
                ('capacidad', models.CharField(max_length=45)),
                ('disponibilidad', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='placa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appEcoindustry.vehiculo'),
            preserve_default=False,
        ),
    ]
