# Generated by Django 4.0.6 on 2022-10-26 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appEcoindustry', '0007_alter_agenda_placa_alter_vehiculo_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='placa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appEcoindustry.vehiculo'),
        ),
    ]
