# Generated by Django 4.0.6 on 2022-10-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEcoindustry', '0009_alter_agenda_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='placa',
            field=models.CharField(max_length=10),
        ),
    ]
