# Generated by Django 4.1 on 2022-11-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appEcoindustry", "0010_alter_agenda_placa"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfoImpacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pesoTotal", models.PositiveIntegerField()),
            ],
        ),
    ]
